export const BLOGS_REQUEST = 'BLOGS_REQUEST';
export const BLOGS_SUCCESS = 'BLOGS_SUCCESS';
export const BLOGS_FAIL = 'BLOGS_FAIL';

export const BLOGS_DETAIL_REQUEST = 'BLOGS_DETAIL_REQUEST';
export const BLOGS_DETAIL_SUCCESS = 'BLOGS_DETAIL_SUCCESS';
export const BLOGS_DETAIL_FAIL = 'BLOGS_DETAIL_FAIL';